
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: whats_cooking_development

test:
  <<: *default
  database: whats_cooking_test
#
production:
  <<: *default
  database: whats_cooking_production
  username: whats_cooking
  password: <%= ENV['WHATS_COOKING_DATABASE_PASSWORD'] %>
